const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const SET_CONTEOS='SET_CONTEOS';
const GET_CONTEOS_SAGA='GET_CONTEOS_SAGA';  
const GENERATE_CSV='GENERATE_CSV'; 
const SET_URL='SET_URL'

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  SET_CONTEOS,
  GET_CONTEOS_SAGA,
  GENERATE_CSV,
  SET_URL
};
